name: Deploy Vite app to GitHub Pages

on:
  push:
    branches: [ main ]    # deploy when main changes
  workflow_dispatch:      # allow manual runs from Actions tab

permissions:
  contents: write          # changed to write so version bump can commit
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Build
        env: 
          CI: 'false'
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist   # Vite output folder

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Bump version patch in package.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          npm version patch -m "ci: bump version to %s [skip ci]"
          git push --follow-tags
